#!/bin/bash
#
# very simple wrapper to compile stg
# w/ or w/o basic prelude
# run make at top level to build stgc binary

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
STGC=$DIR/../codegen/dist/build/stgc/stgc 
RUNTIMEDIR=$DIR/../runtime
FLAGS="-std=gnu99 -L$RUNTIMEDIR -I$RUNTIMEDIR -lruntime"
NAME="$(echo $1 | tr '/' _)"

if [ "$#" -eq 0 ]; then
  echo "usage: $0 infile [outfile] [-no-prelude]"
  exit 1
fi

if [ "${2::1}" == "-" ]; then
  $STGC $1 $2
  exit 0;
fi

if [ "$3" == "-no-prelude" ]; then
  $STGC $1 /tmp/$NAME.$$.c
else 
  (echo "#include \"$DIR/Prelude.stg"\"; cat $1) \
    | cpp -E -P > /tmp/$NAME.$$.stg
  $STGC /tmp/$NAME.$$.stg /tmp/$NAME.$$.c
fi  


if [ "$#" -eq 1 ]; then
  gcc /tmp/$NAME.$$.c $FLAGS
else
  gcc /tmp/$NAME.$$.c -o $2 $FLAGS

fi
